version: '3.8'
services:
  backend:
    build: ./backend
    container_name: biletal-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/biletal
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=development
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: biletal-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:7
    container_name: biletal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 